### ISSUE TITLE
Avoiding position:absolute?

### ISSUE THREAD

**Issue by maxkrieger** [uber/deck.gl#2483]
Apologies if I am not reading the docs close enough. With React, I want to put a `<StaticMap>` (from `react-map-gl`) beneath a `LineLayer`, and contain the `<DeckGL>` element in a css grid parent column. It looks like `position:absolute` is automatically applied to the children of `<DeckGL>`, however. How do I integrate the `<DeckGL>` elements into my existing layout?

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by adriangabardo** [comment]
@maxkrieger Could you maybe share the code? I can't seem to set position: relative on it

**Comment by maxkrieger** [comment]
@adriangabardo set a container, not the DeckGL element itself, to position relative.

**Comment by adriangabardo** [comment]
Literally just figured that out ahahha 
But thanks for the reply :)
Here is the code for future reference:
`<div style={{position:"relative"}}>
            <DeckGL
                {...this.state.viewport}
                initialViewState={initialViewState}
                controller={true}
                layers={layers}
            >
                <MapGL 
                  {...this.state.viewport}
                  mapboxApiAccessToken={MAPBOX_ACCESS_TOKEN}
                />
            </DeckGL>
          </div>`

**Comment by aaronsamkennedy** [comment]
I tried to do this in our app and it only by changing the positioning to relative in the wrapping div it seems to be breaking our map and resulting in the warning: luma: Device pixel ratio clamped. When we add the wrapper style the deck component seems to break, a map shows up but with no controls, no viewport and not added layers. 

The map works perfectly without it. Any idea why this might cause the deck component to break? 

```
<div style={{position:'relative'}}> 
      <DeckGL
        layers={renderLayers({ 
          data: getRuns(geo),
          selected:props.selection,
          onHover: hover => _onHover(hover)})}
        getCursor={() => hover.hoveredObject ? 'pointer' : 'default'} 
        initialViewState={INITIAL_VIEW_STATE}
        controller={true}
        onClick={(click) => _onClick(click)}
      >
        <StaticMap 
          mapboxApiAccessToken={MAPBOX_TOKEN}
          mapStyle={MAPBOX_STYLE} />
      </DeckGL>
    </div>
```

**Comment by masonlr** [comment]
I had similar issues, that were resolved by explicitly adding height and width attributes to the wrapping div, for example:

```
<div style={{ height: "50vh", width: "50vw", position: "relative" }}>
...
</div>
```

**Comment by jameskerry651** [comment]
@masonlr 
this is effictive, but when i try to draged this map with mouse, which can't be draged.

**Comment by xinaesthete** [comment]
In my case, I was having fairly decent results with Deck having `position: relative` until I started trying to display tooltips... adding a wrapping div is causing nothing but problems for me, so far. Doesn't fix the tooltip position, breaks my deck canvas layout.

**Comment by lucgirardin** [comment]
I find it very useful, for example if one need to have a timestamp stored in a file name, in my case `weather-20250415T065500Z.parquet`.
